baseURL = ''
languageCode = 'en-us'
title = ':evergreen_tree: Saqibs Notes'
theme = 'archie'
copyright = 'Saqib Ali ©' 

[params]
mode= "toggle"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/saqibali-2k"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://ca.linkedin.com/in/saqib-ali-toronto"

# Main menu Items

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "notes"
url = "/notes"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3
